name: $(date:yyyyMMdd)$(rev:.rr)

pr:
  - master

stages:
  - stage: build
    jobs:
      - job:
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: dotnet build

  - stage: test
    jobs:
      - job:
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: dotnet test --collect:"XPlat Code Coverage"
            

  - stage: pack
    jobs:
      - job:
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: |
              docker login
              docker image build -f dockerfile -t april13/p1proj .
              docker image push april13/p1proj
              docker logout

trigger:
  - master
